### ISSUE TITLE
Compiler Tool Chain for Developers

### ISSUE THREAD

**Issue by yufeiminds** [GuanceCloud/ppl#21]
## Proposal

* [A001 - Add compiler toolchain for developers](https://github.com/GuanceCloud/ppl/blob/13e6f48d3c87861a697c668ca83827f11ecbb89f/proposals/A001-add-developer-toolchain.md)

### VSCode

* [x] Support for **syntax highlighting** (#18)
* [x] Support for **code completion** (#18)
* [x] Support for **code linting** (#18)
* [x] Support for **code formatting** (#18)
* [ ] Support for **code navigation**
* [ ] Support for **code refactoring**
* [ ] Support for **vulnerability detection**

### JetBrains

* [ ] Support for **syntax highlighting**
* [ ] Support for **code completion**
* [ ] Support for **code linting**
* [ ] Support for **code formatting**
* [ ] Support for **code navigation**
* [ ] Support for **code refactoring**
* [ ] Support for **vulnerability detection**

### Others

* [ ] GitHub Linguist
* [ ] DevContainer / CodeSpaces
* [ ] GitPod Editor
